name: Ryuuganime JSON Database Validator

on:
    pull_request:
    push:
        branches:
        - master

jobs:
    validate:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v1
        - name: Validate JSON
          uses: OrRosenblatt/validate-json-action@0.1.0
          env:
            INPUT_SCHEMA: ./schema.json
