name: Ryuuganime JSON Database Validator

on:
    pull_request:
    push:
        branches:
        - master

jobs:
    validate:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v1
        - name: Validate JSON
          uses: docker://orrosenblatt/validate-json-action:latest
          env:
            INPUT_SCHEMA: ./schema.json
            INPUT_JSONS: ./json/1.json, ./json/2.json, ./json/3.json, ./json/4.json, ./json/5.json
